spring:
    datasource:
        driverClassName: org.postgresql.Driver
        url: jdbc:postgresql://localhost:5432/ec-202504b
        username: postgres
        password: postgres
server:
    servlet:
        context-path: /ec